#!/bin/bash
# NEXTFLOW TASK: trim (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/icipe/bsgke/input/work/52/90f945bf833b0428a0aaa15ef51e6d/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /home/icipe/bsgke/input/work/52/90f945bf833b0428a0aaa15ef51e6d/.command.begin
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f SRR957824_500K_R1.fastq.gz
rm -f SRR957824_500K_R2.fastq.gz
rm -f SRR957824_500K_R1_fastqc.html
rm -f SRR957824_500K_R1_fastqc.zip
rm -f SRR957824_500K_R2_fastqc.html
rm -f SRR957824_500K_R2_fastqc.zip
ln -s /home/icipe/bsgke/input/data/SRR957824_500K_R1.fastq.gz SRR957824_500K_R1.fastq.gz
ln -s /home/icipe/bsgke/input/data/SRR957824_500K_R2.fastq.gz SRR957824_500K_R2.fastq.gz
ln -s /home/icipe/bsgke/input/work/b5/ade8343acc33fb32860df2e935bf81/SRR957824_500K_R1_fastqc.html SRR957824_500K_R1_fastqc.html
ln -s /home/icipe/bsgke/input/work/b5/ade8343acc33fb32860df2e935bf81/SRR957824_500K_R1_fastqc.zip SRR957824_500K_R1_fastqc.zip
ln -s /home/icipe/bsgke/input/work/b5/ade8343acc33fb32860df2e935bf81/SRR957824_500K_R2_fastqc.html SRR957824_500K_R2_fastqc.html
ln -s /home/icipe/bsgke/input/work/b5/ade8343acc33fb32860df2e935bf81/SRR957824_500K_R2_fastqc.zip SRR957824_500K_R2_fastqc.zip

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash -ue /home/icipe/bsgke/input/work/52/90f945bf833b0428a0aaa15ef51e6d/.command.sh
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
